Revert "spes: libinit: Workaround safetynet"
Fixes error:

    device/xiaomi/spes/libinit/init_xiaomi_spes.cpp:59:5: error: use of undeclared identifier 'property_override'
    property_override("ro.boot.verifiedbootstate", "green");

This reverts commit 017199effd2f71f41b648c29b4689b161f16bf72.